### ISSUE TITLE
v-text-field clearable style

### ISSUE THREAD

**Issue by Henvy-Mango** [userquin/vuetify-nuxt-icon-integration#1]
When using v-text-field with the clearable option, the close button's style appears odd.
How can Fix it?
```html
    <v-text-field label="test" clearable></v-text-field>
```

![image](https://github.com/userquin/vuetify-nuxt-icon-integration/assets/33375791/c2b9781d-9fe8-4fd7-aeb4-fce61ddc8efd)

**Comment by Henvy-Mango** [comment]
svg-icon and css-icon will both appears this problem

**Comment by userquin** [comment]
I dont use nuxt icon, check if you can scale the icon like on unplugin-icons and unocss icons preset, the icon is too big.

**Comment by Henvy-Mango** [comment]
It seems like a nuxt icon issue, I compared with unplugin-icons and found that the rendered SVG item has unexpected class attributes, so even if the default icon size has changed, it will not work.

![image](https://github.com/userquin/vuetify-nuxt-icon-integration/assets/33375791/a94bf094-a1ed-4d70-bb48-6458b1ce451e)

**Comment by userquin** [comment]
you can try using the [clear slot](https://vuetifyjs.com/en/components/text-fields/#slots)  : not documented in v-text-field but can be found here https://vuetifyjs.com/en/api/v-text-field/#slots-clear

**Comment by Henvy-Mango** [comment]
Thank you very much! It backs to normal now.
This is a temporary solution.
```vue
<v-text-field v-model="query" clearable>
  <template #clear>
    <Icon name="i-mdi:close-circle" @click="query = ''" />
  </template>
</v-text-field>
```
